### ISSUE TITLE
[Remove] modrinth-app-git

### ISSUE THREAD

**Issue by Rattlyy** [chaotic-aur/packages#2723]
### Package

https://aur.archlinux.org/packages/modrinth-app-git

### Purpose

Unofficial minecraft mod launcher

Has backing of the biggest mod store for minecraft, will be very useful once out

### License

https://github.com/modrinth/code?tab=License-1-ov-file

**Comment by xiota** [comment]
Please use the license name for commonly used, named licenses, like GPL.

What does, "will be very useful once out" mean?

**Comment by FabioLolix** [comment]
This fail yo build in chroot https://aur.archlinux.org/packages/modrinth-app-git#comment-929897 , fixable

**Comment by Rattlyy** [comment]
@xiota Modrinth is very popular and it's community has a lot of arch users. The launcher is currently in beta, and once it's fully out it will probably become one of the most used ones, so lots of downloads.

@FabioLolix was fixed

**Comment by Technetium1** [comment]
I left [a comment for the maintainer](https://aur.archlinux.org/packages/modrinth-app-git#comment-932361) since `cargo` is still missing. It can be added when it builds.

**Comment by xiota** [comment]
Fails to build. Issue was noted in aurweb comment dated 2024-07-09.

**Comment by xiota** [comment]
Fails to build.  I suspect missing depends, indirectly required through Rust package.  These indirect requirements tend to be very difficult to track down.  Metrics 363.

**Comment by xiota** [comment]
Removed patch with [interfere](https://github.com/chaotic-aur/packages/commit/e82f554df413d42691408b84c6f4d2541db18152).

**Comment by xiota** [comment]
Fails to build.  Adding `--loglevel debug` to `pnpm` commands shows following:
```
│  ERROR  [GET] "https://staging-api.modrinth.com/v2/tag/report_type": 500 Internal Server Error
```
Description from server is:
```
Database Error: Redis Pool Error: Error occurred while creating a new object: An error was signalled by the server - ReadOnly: You can't write against a read only replica.
```

**Comment by xiota** [comment]
Dropping because license disallows redistribution.  This may have been a license change.  The project was switched to a different repo with no history of the old LICENSE file.

From https://github.com/modrinth/code?tab=License-1-ov-file

> **Modrinth Branding**
> 
> The use of Modrinth branding elements, including but not limited to the wrench-in-labyrinth logo, the landing image, and any variations thereof, is **strictly prohibited without explicit written permission** from Rinth, Inc. This includes trademarks, logos, or other branding elements.
> https://github.com/modrinth/code
> > All rights reserved. © 2020-2024 Rinth, Inc.
> 
> This includes, but may not be limited to, the following files:
> 
> * idea/icon.svg
> 
> If you fork this repository, **you must remove all Modrinth branding assets** from your fork.

Also, failing to build for over a month.

Metrics 214.
