### ISSUE TITLE
[Request] nbtworkbench-git

### ISSUE THREAD

**Issue by kittenvr** [chaotic-aur/packages#3664]
### Package

https://aur.archlinux.org/packages/nbtworkbench-git

### Purpose

Minecraft Named Binary Tag (NBT) editor

Reference: https://minecraft.wiki/w/NBT_format

### License

Mozilla Public License Version 2.0

### Submission checklist

- [x] The package is not banned.
- [x] The package is not available in Chaotic AUR or official Arch repos.
- [x] The package has not already been requested.

**Comment by xiota** [comment]
"Purpose" should describe what the application is used for.  Package and upstream description are vague, referencing something called NBT, but the link that's supposed to describe what it is times out.  Search and AI are not helpful, stating it could be Next Big Thing, NetBIOS over TCP/IP, Named Binary Tag, Nano Biotechnology, Non-Blocking Time...

**Comment by RealRTTV** [comment]
I can try and make the aur description more descriptive by now

**Comment by xiota** [comment]
Project readme does not mention "named binary tag" or minecraft.  However, since you mentioned it, I now see it is tagged minecraft.

**Comment by xiota** [comment]
Here's a page that might be suitable to replace the one in the readme that times out.
```
https://minecraft.fandom.com/wiki/NBT_format
```

**Comment by kittenvr** [comment]
or this one https://minecraft.wiki/w/NBT_format

**Comment by RealRTTV** [comment]
+ I just updated the package categories to include `minecraft` to help aid people in searching for what NBT means if they didn't check the gh page for whatever reason

**Comment by xiota** [comment]
The minecraft.wiki link wasn't working earlier.

**Comment by Technetium1** [comment]
@RealRTTV please add `git` to `makedepends`. It still fails to build:
```
Compiling xml-rs v0.8.26
error[E0554]: `#![feature]` may not be used on the stable release channel
--> /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hashbrown-0.15.3/src/lib.rs:15:5
|
15 | /     feature(
16 | |         test,
17 | |         core_intrinsics,
18 | |         dropck_eyepatch,
...  |
24 | |         strict_provenance_lints
25 | |     )
| |_____^
```

**Comment by RealRTTV** [comment]
on it!

**Comment by xiota** [comment]
> It includes "NBT" and a hyperlink to the documentation ... didn't check the gh page for whatever reason

Prior to recent commit, "hyperink to the documentation" was broken and host (`wiki.vg`) did not contain relevant semantic information.

> I just updated the package categories to include minecraft to help aid people in searching for what NBT means

Categories do not show in pacman search.  They also do not show in aurweb search.  Recommend changing the description to something like "A Minecraft Named Binary Tag (NBT) editor written in Rust".

**Comment by RealRTTV** [comment]
ok i'll do that then!

**Comment by xiota** [comment]
Also recommend changing `source` to following:
```
source=("git+$url.git")
```
Because some systems / network config have problems redirecting.

**Comment by RealRTTV** [comment]
did that too

**Comment by xiota** [comment]
```
error: no such command: `+nightly`
```

To use nightly, add `rustup` to makedeps.  Then setting `RUSTUP_TOOLCHAIN=nightly` should be sufficient.

**Comment by RealRTTV** [comment]
the libraries have to compile with nightly too, so hopefully that'll fix it

**Comment by RealRTTV** [comment]
> ```
> error: no such command: `+nightly`
> ```
> 
> To use nightly, add `rustup` to makedeps. Then setting `RUSTUP_TOOLCHAIN=nightly` should be sufficient (can remove +nightly from individual calls). Tested that build succeeds with these changes.
> 
> If you test [building in a clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot), would be easier to identify missing deps and other issues.

lovely to hear, i had issues the past with non-nightly branches trying to compile `hashbrown` with the nightly feature and it causing issues, hopefully adding `rustup` here fixes it.

thank you so much for your help <3

**Comment by RealRTTV** [comment]
anything else I should add before this is a closed issue?

**Comment by xiota** [comment]
Looks okay to me.  Added.

For future reference, commenting after making requested changes is sufficient.  Unless clarification is needed, commenting before isn't too useful.

-git packages tend to be low maintenance, but if you find yourself short on time, or prefer to focus on upstream development, you can consider adding a comaintainer. 

If you need someone's attention, you can comment here or ping at the relevant issue.

**Comment by kittenvr** [comment]
so its added to chaoticaur right, i dont see it yet might take some time to update

**Comment by Technetium1** [comment]
@kittenvr it is available for a while now, you should absolutely see it.

**Comment by xiota** [comment]
@kittenvr Build was already complete before I closed this issue.  If you already had the same version installed, you won't see an update until the next rebuild.  If you don't see it in pacman search, you would need to provide more info so someone can check the mirror you're using.
```
$ sudo pacman -Sy

$ pacman -Ss nbtworkbench
chaotic-aur/nbtworkbench-git 1.6.2-1
    A modern NBT (Minecraft's Named Binary Tags) Editor written in Rust.
```

**Comment by kittenvr** [comment]
i use yay not pacman

**Comment by xiota** [comment]
You should switch to pacman.  But seriously, no significant difference.
```
$ yay -Sy

$ yay -Ss nbtworkbench
aur/nbtworkbench-git 1.6.2-1 (+0 0.00)
    A modern NBT (Minecraft's Named Binary Tags) Editor written in Rust.
chaotic-aur/nbtworkbench-git 1.6.2-1 (4.1 MiB 9.2 MiB)
    A modern NBT (Minecraft's Named Binary Tags) Editor written in Rust.
```

**Comment by kittenvr** [comment]
after yay -Sy its there now thanks

**Comment by RealRTTV** [comment]
> Looks okay to me.  Added.
> 
> For future reference, commenting after making requested changes is sufficient.  Unless clarification is needed, commenting before isn't too useful.
> 
> AUR sends update notifications.  So if someone requests a change on aurweb, comments after the change aren't needed.
> 
> -git packages tend to be low maintenance, but if you find yourself short on time, or prefer to focus on upstream development, you can consider adding a comaintainer. 
> 
> If you need someone's attention, you can comment here or ping at the relevant issue.

Is there anything recommended to do to help making releasing new versions more automatic for you guys, or is a simple ping every time I `git push` a new update enough?

**Comment by RealRTTV** [comment]
and just to confirm, I comment something like "new version" and that's all I need to do for you guys to sync to the newest commit to the aur entry?

**Comment by Technetium1** [comment]
> i use yay not pacman

@kittenvr Using an AUR helper for something available in repositories that Pacman can access is not the best, but you _can_... https://wiki.archlinux.org/title/AUR_helpers



> all I need to do for you guys to sync to the newest commit

@RealRTTV Just push a change to your repo. There is infrastructure in place to pull the latest commit and build using the AUR package. There should be no need for your intervention at all now that it has been added.

**Comment by xiota** [comment]
@RealRTTV Your question prompted me to notice that I missed something... Your package needs a `pkgver()` function.  The following works:
```
pkgver() {
  cd nbtworkbench
  git describe --long --tags --abbrev=7 --exclude='*[a-zA-Z][a-zA-Z]*' \
    | sed -E 's/^[^0-9]*//;s/([^-]*-g)/r\1/;s/-/./g'
}
```
Many put it before `prepare()`, but keep in mind that `makepkg` runs it after.  Before pushing changes, build the package and run `makepkg --printsrcinfo | tee .SRCINFO`.  Since pkgver is calculated on demand, don't push updates to -git packages for mere version bumps.

Then as Technetium1 indicated, chaotic-aur servers will poll for changes and rebuild when it detects changes in the package or upstream repo.

**Comment by RealRTTV** [comment]
sorry i saw this so late, absolutely brilliant idea, i'll be using that to fix it, thank you so much

**Comment by RealRTTV** [comment]
really fun how i lost my ssh key and somehow resetting it doesn't work

**Comment by xiota** [comment]
@RealRTTV Any luck with key recovery?  Can you enter a new key in your AUR account?  Does this affect the upstream repo?

**Comment by RealRTTV** [comment]
I'm taking a bit of a break from nbtworkbench right now, the large refactor has been tedious and difficult. If chaotic-aur could use the most recent compiling build, that'd be best. I'll revisit the project at some point.

Sorry.

**Comment by xiota** [comment]
Would you mind adding me as comaintainer of the AUR package so I can update it?

`pkgver()` needs to be added, and it's failing to build (haven't looked for reason yet).

**Comment by RealRTTV** [comment]
absolutely.

**Comment by RealRTTV** [comment]
`xiota` i assume?

**Comment by xiota** [comment]
Yes.  Thank you.

**Comment by pizzav-xyz** [comment]
@xiota 

<img width="1660" height="641" alt="Image" src="https://github.com/user-attachments/assets/b93d9be5-5d43-42f9-b6f7-b833e5fc014b" />

**Comment by Technetium1** [comment]
@kittenvr Please upgrade & refresh databases: `sudo pacman -Syu nbtworkbench-git`
https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported
