### ISSUE TITLE
[Request] helion

### ISSUE THREAD

**Issue by JustinWayland** [chaotic-aur/packages#3845]
### Package

https://aur.archlinux.org/pkgbase/helion

### Purpose

Doom source port focused on performance over demo compatibility.  Much faster than DSDA Doom, especially on decade+ old hardware.

### License

GPL-3.0-or-later

### Submission checklist

- [x] The package is not banned.
- [x] The package is not available in Chaotic AUR or official Arch repos.
- [x] The package has not already been requested.

**Comment by JustinWayland** [comment]
I will note in the interest of transparency that the git version of this package has already been requested.

I am involved with Helion and am a co-maintainer of the AUR package.  If you have any issues, please let me know and I'll make relevant changes.

**Comment by xiota** [comment]
Looking at request for the -git package, looks like I intended to add it, but forgot.  Is there any reason to prefer one package over the other or should both be added?

**Comment by JustinWayland** [comment]
Probably just plain Helion.  We currently do releases semi-regularly, but on my 7840HS it takes a solid 30-35s to compile.  Don't want to put more of a burden on your build architecture.

**Comment by xiota** [comment]
@JustinWayland While trying to build this, seeing following error:
```
==> ERROR: Failure while downloading https://github.com/Helion-Engine/Helion/archive/refs/tags/helion-0.9.8.0.tar.gz
```

On releases page, looks like link should be:
```
https://github.com/Helion-Engine/Helion/archive/refs/tags/0.9.8.0.tar.gz
```

**Comment by JustinWayland** [comment]
Fixed it.

**Comment by spinktvis** [comment]
Installed the package, except the command helion and the .desktop shortcut are both missing in the console/menu. 

Trying to launch the .desktop file manually gives error: The desktop entry file /usr/share/applications/Helion.desktop is not valid.

**Comment by JustinWayland** [comment]
Had to install Helion to /opt/bin/Helion due to limitations with that
version in particular.  The next release should have it in a more standard
place.

I’ll try to figure out why the .desktop file isn’t working when I am not
running late for class.

**Comment by spinktvis** [comment]
Thanks for the effort, let me know if you need a tester!

**Comment by JustinWayland** [comment]
Alright, I uploaded a new revision of the PKGBUILD to the AUR.  Once the ChaoticAUR gets it, the .desktop file should work now.

Also, the path is ```/opt/Helion/Helion```.  That last comment was written in a rush, sorry.

The next release will use more standard directories for everything, so it should show up on your PATH then.

**Comment by spinktvis** [comment]
Quick update: just tried the latest build, same problem persists, the .desktop file is still invalid, and the helion command itself is not found. This is on KDE Plasma.

Worked around the .desktop problem by deleting the TryExec line (line 6) which at least allows it to show up in the application launcher menu.

**Comment by xiota** [comment]
@JustinWayland Easiest way to fix package is to leave the upstream .desktop file alone and put a script at /usr/bin/Helion.
```
package() {
  # ...
  install -Dm755 /dev/stdin "$pkgdir/usr/bin/Helion" << END
#!/usr/bin/env sh
exec /opt/Helion/Helion
END
}
```

According to KDE docs, [Desktop file](https://develop.kde.org/docs/features/desktop-file/):

> The command passed to TryExec is used to test to see if the application is actually installed on the system. That is to say, if a command cannot be accessed from the $PATH (usually the case when the user creates their own custom .desktop files and uninstalls the application), the entry will not show up on the menu.

**Comment by JustinWayland** [comment]
Not again...

I'll fix this later, when I'm not in class.

**Comment by JustinWayland** [comment]
OK, I've removed TryExec altogether until the next point release in November, when we can use upstream's .desktop file.
